/* =================================================================
   AYOH LUXURY BOUAKÉ — data.js
   Source UNIQUE des produits. Chaque produit n'existe qu'une fois ici.
   Les pages Gammes et Catégories ne font que FILTRER ce tableau.
   ================================================================= */

const PRODUCTS = [
  // ---------- Hoyibo Cacao ----------
  { id: "kit-hoyibo-cacao", name: "Kit Hoyibo Cacao", gamme: "Hoyibo Cacao", gammeSlug: "hoyibo-cacao", categorie: "Kit", categorieSlug: "kit", price: 63000, description: "Gamme clarifiante, régénérante et hydratante pour teint noir et marron, qui prend soin de la peau en profondeur.", ingredients: "Poudre de cacao, glycérine, vitamine C, huiles essentielles", image: "kit-hoyibo-cacao.jpg", hasCard: true },
  { id: "lait-corps-hoyibo-cacao", name: "Lait Corps Hoyibo Cacao", gamme: "Hoyibo Cacao", gammeSlug: "hoyibo-cacao", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 15000, description: "Gamme clarifiante, régénérante et hydratante pour teint noir et marron, qui prend soin de la peau en profondeur.", ingredients: "Poudre de cacao, glycérine, vitamine C, huiles essentielles", image: "lait-corps-hoyibo-cacao.jpg", hasCard: true },
  { id: "huile-corps-hoyibo-cacao", name: "Huile Corps Hoyibo Cacao", gamme: "Hoyibo Cacao", gammeSlug: "hoyibo-cacao", categorie: "Huiles Corps", categorieSlug: "huiles-corps", price: 7000, description: "Gamme clarifiante, régénérante et hydratante pour teint noir et marron, qui prend soin de la peau en profondeur.", ingredients: "Poudre de cacao, glycérine, vitamine C, huiles essentielles", image: "huile-corps-hoyibo-cacao.jpg", hasCard: true },
  { id: "gel-douche-hoyibo-cacao", name: "Gel Douche Hoyibo Cacao", gamme: "Hoyibo Cacao", gammeSlug: "hoyibo-cacao", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 15000, description: "Gamme clarifiante, régénérante et hydratante pour teint noir et marron, qui prend soin de la peau en profondeur.", ingredients: "Poudre de cacao, glycérine, vitamine C, huiles essentielles", image: "gel-douche-hoyibo-cacao.jpg", hasCard: true },
  { id: "savon-corps-hoyibo-cacao", name: "Savon Corps Hoyibo Cacao", gamme: "Hoyibo Cacao", gammeSlug: "hoyibo-cacao", categorie: "Savons Corps", categorieSlug: "savons-corps", price: 13000, description: "Gamme clarifiante, régénérante et hydratante pour teint noir et marron, qui prend soin de la peau en profondeur.", ingredients: "Poudre de cacao, glycérine, vitamine C, huiles essentielles", image: "savon-corps-hoyibo-cacao.jpg", hasCard: true },
  { id: "creme-visage-hoyibo-cacao", name: "Crème Visage Hoyibo Cacao", gamme: "Hoyibo Cacao", gammeSlug: "hoyibo-cacao", categorie: "Crèmes Visage", categorieSlug: "cremes-visage", price: 7000, description: "Gamme clarifiante, régénérante et hydratante pour teint noir et marron, qui prend soin de la peau en profondeur.", ingredients: "Poudre de cacao, glycérine, vitamine C, huiles essentielles", image: "creme-visage-hoyibo-cacao.jpg", hasCard: true },

  // ---------- Yoyo Fresh ----------
  { id: "kit-yoyo-fresh", name: "Kit Yoyo Fresh", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Kit", categorieSlug: "kit", price: 84000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "kit-yoyo-fresh.jpg", hasCard: true },
  { id: "lait-corps-yoyo-fresh-grand-format", name: "Lait Corps Yoyo Fresh (grand format)", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 20000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "lait-corps-yoyo-fresh-grand-format.jpg", hasCard: true },
  { id: "huile-corps-yoyo-fresh", name: "Huile Corps Yoyo Fresh", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Huiles Corps", categorieSlug: "huiles-corps", price: 10000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "huile-corps-yoyo-fresh.jpg", hasCard: true },
  { id: "gel-douche-yoyo-fresh-petit-format", name: "Gel Douche Yoyo Fresh (petit format)", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 9000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "gel-douche-yoyo-fresh-petit-format.jpg", hasCard: true },
  { id: "gel-douche-yoyo-fresh-grand-format", name: "Gel Douche Yoyo Fresh (grand format)", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 17000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "gel-douche-yoyo-fresh-grand-format.jpg", hasCard: true },
  { id: "savon-visage-yoyo-fresh", name: "Savon Visage Yoyo Fresh", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Savons Visage", categorieSlug: "savons-visage", price: 5000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "savon-visage-yoyo-fresh.jpg", hasCard: true },
  { id: "creme-visage-yoyo-fresh", name: "Crème Visage Yoyo Fresh", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Crèmes Visage", categorieSlug: "cremes-visage", price: 8000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "creme-visage-yoyo-fresh.jpg", hasCard: true },
  { id: "creme-reparatrice-yoyo-fresh", name: "Crème réparatrice Yoyo Fresh", gamme: "Yoyo Fresh", gammeSlug: "yoyo-fresh", categorie: "Crèmes Visage", categorieSlug: "cremes-visage", price: 20000, description: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair.", ingredients: "Vaseline, acide stéarique, huile blanchissante aux fruits, vitamines E, C, A", image: "creme-reparatrice-yoyo-fresh.jpg", hasCard: true },

  // ---------- Yoyo Fresh Gold ----------
  { id: "kit-yoyo-fresh-gold", name: "Kit Yoyo Fresh Gold", gamme: "Yoyo Fresh Gold", gammeSlug: "yoyo-fresh-gold", categorie: "Kit", categorieSlug: "kit", price: 73500, description: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair. Elle exfolie la peau, éclaircit les zones sombres du corps et redonne éclat et fermeté. Cette gamme propose également une huile corps et un kit visage.", ingredients: "Huile éclaircissante, glycérine, collagène, acide salicylique, acide de fruits, papaye", image: "kit-yoyo-fresh-gold.jpg", hasCard: true },
  { id: "lait-corps-yoyo-fresh-gold", name: "Lait Corps Yoyo Fresh Gold", gamme: "Yoyo Fresh Gold", gammeSlug: "yoyo-fresh-gold", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 20000, description: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair. Elle exfolie la peau, éclaircit les zones sombres du corps et redonne éclat et fermeté.", ingredients: "Huile éclaircissante, glycérine, collagène, acide salicylique, acide de fruits, papaye", image: "lait-corps-yoyo-fresh-gold.jpg", hasCard: true },
  { id: "gel-douche-yoyo-fresh-gold-petit-format", name: "Gel Douche Yoyo Fresh Gold (petit format)", gamme: "Yoyo Fresh Gold", gammeSlug: "yoyo-fresh-gold", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 10000, description: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair.", ingredients: "Huile éclaircissante, glycérine, collagène, acide salicylique, acide de fruits, papaye", image: "gel-douche-yoyo-fresh-gold-petit-format.jpg", hasCard: true },
  { id: "gel-douche-yoyo-fresh-gold-grand-format", name: "Gel Douche Yoyo Fresh Gold (grand format)", gamme: "Yoyo Fresh Gold", gammeSlug: "yoyo-fresh-gold", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 18000, description: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair.", ingredients: "Huile éclaircissante, glycérine, collagène, acide salicylique, acide de fruits, papaye", image: "gel-douche-yoyo-fresh-gold-grand-format.jpg", hasCard: true },
  { id: "gommage-corps-yoyo-fresh-gold", name: "Gommage Corps Yoyo Fresh Gold", gamme: "Yoyo Fresh Gold", gammeSlug: "yoyo-fresh-gold", categorie: "Gommages Corps", categorieSlug: "gommages-corps", price: 8000, description: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair. Exfolie la peau et éclaircit les zones sombres du corps.", ingredients: "Huile éclaircissante, glycérine, collagène, acide salicylique, acide de fruits, papaye", image: "gommage-corps-yoyo-fresh-gold.jpg", hasCard: true },
  { id: "savon-calendula", name: "Savon Calendula", gamme: "Yoyo Fresh Gold", gammeSlug: "yoyo-fresh-gold", categorie: "Savons Corps", categorieSlug: "savons-corps", price: 2500, description: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair.", ingredients: "Huile éclaircissante, glycérine, collagène, acide salicylique, acide de fruits, papaye, calendula", image: "savon-calendula.jpg", hasCard: true },
  { id: "kit-visage-yoyo-fresh-gold", name: "Kit Visage Yoyo Fresh Gold", gamme: "Yoyo Fresh Gold", gammeSlug: "yoyo-fresh-gold", categorie: null, categorieSlug: null, price: null, description: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair.", ingredients: null, image: null, hasCard: false },

  // ---------- Black to White ----------
  { id: "kit-black-to-white", name: "Kit Black to White", gamme: "Black to White", gammeSlug: "black-to-white", categorie: "Kit", categorieSlug: "kit", price: 103000, description: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé. Traitante, blanchissante, régénérante et adoucissante. Cette gamme propose également un kit visage.", ingredients: "Vitamines E et C, glutathion, collagène, acide de fruits", image: "kit-black-to-white.jpg", hasCard: true },
  { id: "lait-corps-black-to-white-petit-format", name: "Lait Corps Black to White (Petit format)", gamme: "Black to White", gammeSlug: "black-to-white", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 17000, description: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé. Traitante, blanchissante, régénérante et adoucissante.", ingredients: "Vitamines E et C, glutathion, collagène, acide de fruits", image: "lait-corps-black-to-white-petit-format.jpg", hasCard: true },
  { id: "lait-corps-black-to-white-grand-format", name: "Lait Corps Black to White (Grand format)", gamme: "Black to White", gammeSlug: "black-to-white", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 35000, description: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé. Traitante, blanchissante, régénérante et adoucissante.", ingredients: "Vitamines E et C, glutathion, collagène, acide de fruits", image: "lait-corps-black-to-white-grand-format.jpg", hasCard: true },
  { id: "gel-douche-black-to-white", name: "Gel Douche Black to White", gamme: "Black to White", gammeSlug: "black-to-white", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 15000, description: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé.", ingredients: "Vitamines E et C, glutathion, collagène, acide de fruits", image: "gel-douche-black-to-white.jpg", hasCard: true },
  { id: "gommage-corps-black-to-white", name: "Gommage Corps Black to White", gamme: "Black to White", gammeSlug: "black-to-white", categorie: "Gommages Corps", categorieSlug: "gommages-corps", price: 20000, description: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé.", ingredients: "Vitamines E et C, glutathion, collagène, acide de fruits", image: "gommage-corps-black-to-white.jpg", hasCard: true },
  { id: "creme-visage-black-to-white", name: "Crème Visage Black to White", gamme: "Black to White", gammeSlug: "black-to-white", categorie: "Crèmes Visage", categorieSlug: "cremes-visage", price: 8000, description: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé.", ingredients: "Vitamines E et C, glutathion, collagène, acide de fruits", image: "creme-visage-black-to-white.jpg", hasCard: true },
  { id: "kit-visage-black-to-white", name: "Kit Visage Black to White", gamme: "Black to White", gammeSlug: "black-to-white", categorie: null, categorieSlug: null, price: null, description: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé.", ingredients: null, image: null, hasCard: false },

  // ---------- Skin by Zaron ----------
  { id: "kit-corps-skin-by-zaron", name: "Kit Corps Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Kit", categorieSlug: "kit", price: 56000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "kit-corps-skin-by-zaron.jpg", hasCard: true },
  { id: "kit-visage-skin-by-zaron", name: "Kit Visage Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Kit", categorieSlug: "kit", price: 61000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "kit-visage-skin-by-zaron.jpg", hasCard: true },
  { id: "lait-corps-skin-by-zaron", name: "Lait Corps Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 15000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "lait-corps-skin-by-zaron.jpg", hasCard: true },
  { id: "huile-corps-skin-by-zaron", name: "Huile Corps Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Huiles Corps", categorieSlug: "huiles-corps", price: 15000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "huile-corps-skin-by-zaron.jpg", hasCard: true },
  { id: "gel-douche-skin-by-zaron", name: "Gel Douche Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 26000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "gel-douche-skin-by-zaron.jpg", hasCard: true },
  { id: "serum-skin-by-zaron", name: "Sérum Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Sérums", categorieSlug: "serums", price: 12000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "serum-skin-by-zaron.jpg", hasCard: true },
  { id: "toner-skin-by-zaron", name: "Toner Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Toners", categorieSlug: "toners", price: 12000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "toner-skin-by-zaron.jpg", hasCard: true },
  { id: "toner-skin-by-zaron-acide-salicylique", name: "Toner Skin by Zaron Acide Salicylique", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Toners", categorieSlug: "toners", price: 12000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E, acide salicylique", image: "toner-skin-by-zaron-acide-salicylique.jpg", hasCard: true },
  { id: "eau-micellaire-skin-by-zaron", name: "Eau Micellaire Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Démaquillants", categorieSlug: "demaquillants", price: 15000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "eau-micellaire-skin-by-zaron.jpg", hasCard: true },
  { id: "creme-solaire-skin-by-zaron", name: "Crème solaire Skin by Zaron", gamme: "Skin by Zaron", gammeSlug: "skin-by-zaron", categorie: "Protection solaire", categorieSlug: "protection-solaire", price: 10000, description: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau.", ingredients: "Vitamine C, acide glycolique, alpha-arbutine, collagène, vitamine E", image: "creme-solaire-skin-by-zaron.jpg", hasCard: true },

  // ---------- Autres gammes (présentes uniquement dans les pages Catégories) ----------
  { id: "timeless-glow-noir", name: "Timeless Glow Noir", gamme: "Timeless Glow", gammeSlug: "timeless-glow", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 15000, description: "Lait corps éclaircissant qui donne de l'éclat et unifie le teint, nourrit, adoucit et protège la peau. Pour teint clair.", ingredients: "Vitamine E, trétinoïne, acide kojique", image: "timeless-glow-noir.jpg", hasCard: true },
  { id: "timeless-glow-orange", name: "Timeless Glow Orange", gamme: "Timeless Glow", gammeSlug: "timeless-glow", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 15000, description: "Lait corps éclaircissant qui donne de l'éclat en profondeur, unifie le teint, nourrit, adoucit et protège la peau. Pour teint marron clair.", ingredients: "Vitamine E, niacinamide", image: "timeless-glow-orange.jpg", hasCard: true },
  { id: "timeless-glow-jaune", name: "Timeless Glow Jaune", gamme: "Timeless Glow", gammeSlug: "timeless-glow", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 15000, description: "Lait corps qui illumine et protège la peau, estompe les taches. Pour teint marron clair.", ingredients: "Vitamine E, acide férulique", image: "timeless-glow-jaune.jpg", hasCard: true },
  { id: "baby-moon", name: "Baby Moon", gamme: "Baby Moon", gammeSlug: "baby-moon", categorie: "Laits Corps", categorieSlug: "laits-corps", price: 20000, description: "Lait éclaircissant, exfoliant et unifiant qui nourrit et rend la peau plus claire. Pour teint clair.", ingredients: "Glutathion, arbutine, acide de fruits, AHA", image: "baby-moon.jpg", hasCard: true },
  { id: "bismid-huile-corps", name: "Bismid (Huile Corps)", gamme: "Bismid", gammeSlug: "bismid", categorie: "Huiles Corps", categorieSlug: "huiles-corps", price: 15000, description: "Huile corps unifiante qui répare les dommages, réduit la pigmentation et apaise les inflammations. Pour teint clair.", ingredients: "Huile de jojoba, vitamine A, acide kojique, huile de pépins de raisin", image: "bismid-huile-corps.jpg", hasCard: true },
  { id: "bismid-korean-skin", name: "Bismid Korean Skin", gamme: "Bismid", gammeSlug: "bismid", categorie: "Huiles Corps", categorieSlug: "huiles-corps", price: 12000, description: "Huile qui éclaircit, lisse et donne de l'éclat, aide à unifier le teint.", ingredients: "Vitamine E, riz", image: "bismid-korean-skin.jpg", hasCard: true },
  { id: "aveeno", name: "Aveeno", gamme: "Aveeno", gammeSlug: "aveeno", categorie: "Huiles Corps", categorieSlug: "huiles-corps", price: 15000, description: "Huile hydratante et clarifiante conçue pour les peaux très sèches et sensibles sujettes aux démangeaisons. Apaise, calme et répare la barrière cutanée.", ingredients: "Huile d'avoine, huile de jojoba", image: "aveeno.jpg", hasCard: true },
  { id: "nadinola-secret", name: "Nadinola Secret", gamme: "Nadinola Secret", gammeSlug: "nadinola-secret", categorie: "Huiles Corps", categorieSlug: "huiles-corps", price: 15000, description: "Éclaircit les taches et donne de l'éclat, sans hydroquinone.", ingredients: "Vitamine E, actifs naturels unifiants", image: "nadinola-secret.jpg", hasCard: true },
  { id: "gel-douche-ayoh-vitamine-c", name: "Gel Douche Ayoh Vitamine C", gamme: "Ayoh", gammeSlug: "ayoh", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 17000, description: "Gel douche élégance & éclat, pour une peau lumineuse.", ingredients: "Vitamine C, or 24 carats", image: "gel-douche-ayoh-vitamine-c.jpg", hasCard: true },
  { id: "gel-douche-ayoh-niacinamide", name: "Gel Douche Ayoh Niacinamide", gamme: "Ayoh", gammeSlug: "ayoh", categorie: "Gels Douche", categorieSlug: "gels-douche", price: 17000, description: "Aide à renforcer la barrière cutanée, protège la peau des agressions extérieures et de la perte d'hydratation. Pour teint marron.", ingredients: "Niacinamide, vitamine B3", image: "gel-douche-ayoh-niacinamide.jpg", hasCard: true },
  { id: "lemon-black-soap", name: "Lemon Black Soap", gamme: "Lemon Black Soap", gammeSlug: "lemon-black-soap", categorie: "Savons Corps", categorieSlug: "savons-corps", price: 15000, description: "Savon qui exfolie et restaure la peau. Pour tout type de teint, conçu pour les peaux ternes.", ingredients: "Huile de citron, huile de jojoba, carotte", image: "lemon-black-soap.jpg", hasCard: true },
  { id: "nigerian-black-soap", name: "Nigerian Black Soap", gamme: "Nigerian Black Soap", gammeSlug: "nigerian-black-soap", categorie: "Savons Corps", categorieSlug: "savons-corps", price: 18000, description: "Ce savon est fabriqué avec des ingrédients naturels qui aident la peau à révéler la beauté du teint clair pour un éclat incroyable. Son utilisation quotidienne élimine toutes les impuretés et donne du glow et de la douceur à la peau. Pour tout type de peau.", ingredients: "Ingrédients naturels (détail non communiqué)", image: "nigerian-black-soap.jpg", hasCard: true },
  { id: "savon-placali", name: "Savon Placali (Hoyibo Golden Méga Soap)", gamme: "Placali", gammeSlug: "placali", categorie: "Savons Corps", categorieSlug: "savons-corps", price: 20000, description: "L'extraordinaire savon Hoyibo Golden Méga Soap traite les imperfections de la tête aux pieds, pour un blanchiment incontournable. Pour tout type de teint.", ingredients: null, image: "savon-placali.jpg", hasCard: true },
  { id: "orchidee-black-soap", name: "Orchidée Black Soap", gamme: "Orchidée", gammeSlug: "orchidee", categorie: "Savons Corps", categorieSlug: "savons-corps", price: 20000, description: "Nettoie la peau en profondeur, la rend douce et l'éclaircit. Pour tout type de teint. Traite les vergetures et les veines apparentes/varices.", ingredients: "Huile de lys, huile de macadamia, huile de calendula, AHA", image: "orchidee-black-soap.jpg", hasCard: true },
  { id: "orchidee-green-soap", name: "Orchidée Green Soap", gamme: "Orchidée", gammeSlug: "orchidee", categorie: "Savons Corps", categorieSlug: "savons-corps", price: 25000, description: "Pour peaux fragiles, traite les vergetures et veines apparentes. Nettoie la peau en profondeur et la rend douce en l'éclaircissant.", ingredients: "Persil, aloe vera, calendula, moringa, vitamines E et C, glutathion", image: "orchidee-green-soap.jpg", hasCard: true },
  { id: "bismid-korean-secret", name: "Bismid Korean Secret", gamme: "Bismid", gammeSlug: "bismid", categorie: "Crèmes Visage", categorieSlug: "cremes-visage", price: 18000, description: "Apaise les rougeurs, nettoie en profondeur, lisse le grain de peau, éclaircit et unifie le teint. Idéale pour les teints ternes et les peaux irritées.", ingredients: "Niacinamide, vitamine B3, extrait de riz, collagène", image: "bismid-korean-secret.jpg", hasCard: true },
  { id: "bismid-clear-and-white", name: "Bismid Clear & White", gamme: "Bismid", gammeSlug: "bismid", categorie: "Crèmes Visage", categorieSlug: "cremes-visage", price: 10000, description: "Réduit l'apparence des boutons et des taches, nettoie la peau tout en l'unifiant et en estompant les taches.", ingredients: "Arbutine, acide kojique, acide salicylique, vitamine E", image: "bismid-clear-and-white.jpg", hasCard: true },
];

/* Titres/descriptions d'en-tête pour les pages Gammes (menu principal uniquement) */
const GAMME_INFO = {
  "hoyibo-cacao": { title: "Hoyibo Cacao", intro: "Gamme clarifiante, régénérante et hydratante pour teint noir et marron, qui prend soin de la peau en profondeur." },
  "yoyo-fresh": { title: "Yoyo Fresh", intro: "Gamme éclaircissante, régénérante et réparatrice pour embellir la peau, pour teint marron clair et clair." },
  "yoyo-fresh-gold": { title: "Yoyo Fresh Gold", intro: "Gamme extra-blanchissante conçue pour les peaux difficiles, pour teint clair. Elle exfolie la peau, éclaircit les zones sombres du corps et redonne éclat et fermeté." },
  "black-to-white": { title: "Black to White", intro: "Gamme super éclaircissante conçue pour les peaux difficiles, pour teint métissé. Traitante, blanchissante, régénérante et adoucissante." },
  "skin-by-zaron": { title: "Skin by Zaron", intro: "Gamme hydratante, nourrissante et clarifiante adaptée à tous types de peau." },
};

/* Titres pour les pages Catégories (menu principal) */
const CATEGORIE_TITLES = {
  "laits-corps": "Laits Corps",
  "huiles-corps": "Huiles Corps",
  "gels-douche": "Gels Douche",
  "savons-corps": "Savons Corps",
  "gommages-corps": "Gommages Corps",
  "cremes-visage": "Crèmes Visage",
  "savons-visage": "Savons Visage",
  "serums": "Sérums",
  "toners": "Toners",
  "demaquillants": "Démaquillants",
  "protection-solaire": "Protection solaire",
};